### ISSUE TITLE
use system libb64 if found

### ISSUE THREAD

**Issue by klali** [Yubico/yubico-c-client#14]
yubico-c-client should check (or have a switch for checking?) if there's a system libb64 instead of the bundled and in that case use the systems instead.

**Comment by thorduri** [comment]
Debian still does not have a maintainer and the [bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=706894) referenced by @jas4711 is still open.

The project it self seems abandoned (Last change on _sourceforge_ was in 2013).

Differences between our version and what `debian 8.5` is shipping is immaterial -- even missing the fix from [here](https://github.com/Yubico/yubico-c-client/commit/6fcc3d49d1d9b733c5bd04e4e60d400ed97cda40) and the [bug](http://sourceforge.net/tracker/?func=detail&aid=3313901&group_id=152942&atid=785907) filed against `libb64` for this has been open since 2011.

Further, the library has no packages for at least `redhat/centos`, `archlinux`, `openbsd` and `macOS`.

Closing.
